import Head from "next/head";
import Topo from "@/components/Topo";
import LadingPage from "@/components/LadingPage";

export default function Home() {
  return (
  <>
   <Head>
    <title>Vivant</title>
    <meta name='description' content='Generated by create next app'/>
    <meta name='viewport' content='width=device-width, initial-scale=1'/>
    <link rel='icon' href='/favicon.ico'/>
   </Head>

   <Topo/>
   <LadingPage/>
    
  </>
  );
}
