import Head from "next/head";
import Topo from "@/components/Topo";
import LadingPage from "@/components/LadingPage";


export default function Home() {
  return (
    <>
      <Head>
        <title>Vivant</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Topo />
      <LadingPage />

      <div className="flex flex-col justify-center items-center p-4 ">
        <h3 className="text-2xl md:text-3xl text-center mt-8 mb-5">Saiba como escolher o vinho ideal para você!</h3>
        <div class="flex gap-5 flex-col md:flex-row justify-center items-center space-y-4 md:space-y-0 md:space-x-4 mb-12">
          <div class="bg-[#260401] p-6 rounded-lg text-center w-100 h-50">
            <p>
              <p className="text-[#E1D5C2] mb-2 text-[20px]">Para quem ama frescor e leveza:</p> O vinho branco é perfeito para quem busca algo refrescante e leve. Com sabores de frutas como maçã verde e pêssego, ele é ideal para momentos de celebração ou refeições leves, como saladas e frutos do mar.
            </p>
          </div>
          <div class="bg-[#260401] p-6 rounded-lg text-center w-100 h-50 mb-20">
            <p>
              <p className="text-[#E1D5C2] mb-2 text-[20px]">Para quem gosta de algo mais intenso:</p> O vinho tinto é ideal. Com sabores mais encorpados e notas de frutas escuras e especiarias, ele proporciona uma experiência rica e marcante para quem aprecia vinhos com mais personalidade.
            </p>
          </div>
          <div class="bg-[#260401] p-6 rounded-lg text-center w-100 h-50">
            <p>
             <p className="text-[#E1D5C2] mb-2 text-[20px]">Para quem prefere algo mais doce:</p> O vinho rosé é uma ótima opção. Ele tem um equilíbrio entre a leveza do vinho branco e a suavidade do vinho tinto, com sabores de frutas vermelhas e um toque de doçura, ideal para quem gosta de algo mais suave.
            </p>
          </div>
        </div>
      </div>


    </>
  );
}
